name: Deply to GitHub Pages
on:
  push:
    branches:
      - home

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: yarn # default: npm
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist # default: ./public
        github_token: ${{ secrets.GIT_TOKEN }}
        user_name: ${{ secrets.USER_NAME }}
        user_email: ${{ secrets.USER_EMAIL }}
